language: node_js
cache: yarn
node_js:
- '11'
script:
- yarn add bs-platform
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: Js0z6Ddg0Ji11JjtFzhNk/pkAVNalQUxPCSBBaS0IOqNn43+Kw+uZ5BIW9KHiEr1vDi+N0LMVTAWDKEfCnLnHTN5yZBK1Y+TUvz5B3ip9oits/tRvPharcGOMaBg70TBMrmqMyXdzj2smXAUhN2DKqK0hjVNZVUrm6hg3SH+hQ8UWBOWQ9A+bGe3K0XuLZCghtr6myzDoepzHlQltkvNA6xWyGt5bN5tyWL3ymJRJqArpBQCFeFSUVbF2rALL6NCsxL+SHsgvNOm/H5Ilxo2xQH5aMElQ4nHqCyqabjl7ybm0aGiLvz99QutHMJWUIWB7cejwezTEu6vkjGQwMvsJkziseHP4mpDaGfk/QddwkfHO78YhtUgXE9IXUEJuV8qqx70IGOsc0+xr5z44zflg17vF8ft04Bdih7IaZxqdAJzawW3243vOj4ziGZig6BTIa3A3Rmwin5teAUNqPEWkbHMmpKH3QpCbs7oNAA6Vs3yP3exDzCgz98lkafbEIjKHLgFMUMdp9ijjtfxKYlsGyNMAiOfHMQqA2Rel3aJCHCu2HEi/230p/ORPpc3VdIum9K7pQFTFjWmso+f9H1jjuJ4q2gDGLBiVUX3jb1sroxUmj19FbXQzawbDEM6MC1Iuhjj6eG9t1Fl75Srn3H0pPuVfKYFrfOIJgbaAtbUnzY=
